---
# Setup installation repositories
# Standart repository for Debian / Ubuntu (http://www.rabbitmq.com/install-debian.html)

- name: import repository key
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present

- name: add apt repository
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian/ testing main"
    update_cache: yes
    state: present

